### ISSUE TITLE
Use as a library

### ISSUE THREAD

**Issue by G0wd** [freiheit/discord_feedbot#42]
Anyone tried this?

If yes do you mind posting your code/tweaks?

I would like to do that but have no idea how.

**Comment by freiheit** [comment]
Issue #17 had somebody that apparently made it work...

Do you want to have your bot *configure* the feed stuff? Or just have the bot do the feeds into a room and also do whatever else the bot does? Since feedbot doesn't watch messages or respond to anything, I think you could just configure both bots with the same auth and have both logged into the account at once.

Otherwise, I think you'll need to replicate the stuff in "main".

If you do get it working, I'd love to get back some docs on how to make it work and any code changes you had to do to make it work.

**Comment by G0wd** [comment]
I tried to use another bot token and it works, that is what I was looking for.

Is it possible to make the bot not playing anything?

If I comment the line "gameplayed" it shows "github/freiheit/discord_rss_bot", and if I let "gameplayed =" empty it still shows "Playing" with nothing next to it. I would like to hide the "Playing".

Thanks for the help.

**Comment by G0wd** [comment]
I commented the line gameplayed = MAIN.get("gameplayed", "")
in feed2discord.py and it seems to work.

Problem solved for me.
