### ISSUE TITLE
Insane Traffic

### ISSUE THREAD

**Issue by MiningPickaxe** [freiheit/discord_feedbot#50]
Hello,
I use your discord_feedbot on a Linux server and monitor 2 different RSS feeds with the status of my host systems and VMs. But after 2-4 h the Bot uses a lot of traffic. And I mean a real lot. Constantly 200 - 250 mbit/s. If I'm not careful that eats away a few hundreds of Gigabyte easily. Any Ideas on how to solve this?

**Comment by freiheit** [comment]
Can you see where the traffic is going and which direction? Like maybe with
wireshark or tcpdump?

I haven't seen this behavior. I suspect a bug in the discord.py API that
feedbot uses.

Anything unusual about your discord server? Tens of thousands of users?
Room the bot can "see" with thousands of messages a second? Feedbot doesn't
look at that stuff, but I think the API sees it anyways.

**Comment by MiningPickaxe** [comment]
I'm gonna try to do a tcpdump when I start the bot again. 
Unusual things about the discord server? 8 users including the bot and the max messages per minute is maybe 15 or so... Over night we are all sleeping and nobody posts messages. So that should not be the problem.
One rss feed is ~7200 characters long, the other one has ~43000 characters long (should be 43kB if I'm correct) so that could not be the problem either

**Comment by freiheit** [comment]
Oh, also try setting `debug=3` in the .ini file. The default (0) only logs a few things. Turning logging up to 3 also enables debug level logging in some of the libraries and really tells you a lot of what's going on.

For debugging this, you might also try increasing rss_refresh_time so that you can see what's going on when the individual feeds are "sleeping".
